kind = "web"
previewPath = "/"
title = "Khabar"
version = "1.0.0"
id = "artifacts/khabar"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24070

[services.development]
run = "pnpm --filter @workspace/khabar run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/khabar", "run", "build" ]
publicDir = "artifacts/khabar/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24070"
BASE_PATH = "/"
